repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: ['--strict']
        entry: mypy
        language: system

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module']

# -   repo: https://github.com/pre-commit/mirrors-flake8
#    rev: v3.9.0
#    hooks:
#    -   id: flake8
#        args: ['--max-line-length=120']

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.14
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
